### ISSUE TITLE
Adopter pas-à-pas React 19 (via Next.js 15)

### ISSUE THREAD

**Issue by LutherTS** [ReactParis/talks#11]
# Proposition de talk - React Paris

## Description du talk

- Titre : Adopter pas-à-pas React 19 (via Next.js 15)

- Contenu (Décrivez brièvement le contenu de la présentation) : Next.js 15 vient tout juste de devenir stable et offre aujourd'hui le premier framework officiel permettant d'utiliser les dernières nouveautés de React 19 en production. Le but de mon talk et de présenter en deux phases comment passer aux React Server Components (RSC) sur une page web. D'abord en séparant cette page web en un fichier serveur et un fichier client. Puis en séparant ce fichier client lui aussi en un fichier serveur et un fichier client, chacun réunissant l'intégralité respective de ses composants potentiellement serveur et strictement client, en vue d'optimiser progressivement (ou non) le nombre de composants qui seront rendus exclusivement sur le serveur. Ces fameux vrais React Server Components, que nous pourrons observer ensemble avec les React Developer Tools. 

Mon talk se basera essentiellement sur le code d'un de mes projets tournant sur ma machine et ne dépend d'aucune connexion à Internet. Son dépôt GitHub est disponible au lien suivant : https://github.com/LutherTS/tt-solo. Ce sera mon premier talk et j'espère peaufiner sa présentation avec vous sur Discord. J'entends le structurer de la manière suivante : 5 minutes max pour me présenter, 5 minutes max pour présenter la page, 5 minutes pour présenter la version 1 avec le code serveur et le code client, et enfin 5 minutes pour présenter la version 2 où le code client est séparé en un fichier potentiellement serveur et un fichier strictement client, pour un total de 20 minutes.

- Durée :

  - [ ] Lightning (10 minutes)
  - [X] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
    > ⚠️ Veuillez préciser dans la description pourquoi vous avez besoin de plus de temps pour présenter votre sujet. Pour information, les présentations longues ne sont pas prioritaires, car nous préférons avoir plusieurs présentations courtes pour les participants à l'événement.

- Niveau :
  - [X] Débutant
  - [ ] Intermédiaire
  - [ ] Avancé

## A propos de vous

- Nom et prénom : Luther Tchofo Safo
- Contact (X / LinkedIn / Autre) : https://www.linkedin.com/in/luther-tchofo-safo/
- Entreprise : actuellement à mon compte
- Rôle dans l'entreprise : développeur web full-stack React

**Comment by gpichot** [comment]
Hello @LutherTS,
Comme on en avait discuté pour le meetup dernier, on te cale sur le meetup du 20 novembre.
Est-ce que c'est bon pour toi ?

Je te contacte sur LinkedIn pour qu'on voie ensemble les détails.

**Comment by LutherTS** [comment]
Absolument, c'est bon pour moi.

**Comment by gpichot** [comment]
Done !
