### ISSUE TITLE
Les nouveautés de React 19 et comment les utiliser ?

### ISSUE THREAD

**Issue by cchalop1** [ReactParis/talks#4]
# Proposition de talk - React Paris

## Description du talk

- Titre : React 19 

- Contenu (Décrivez brièvement le contenu de la présentation) :

Présentation des nouvelles fonctionnalités de React, 19. 

Comment on les utilisait avec des exemples concrets.

- Durée :

  - [X] Lightning (10 minutes)
  - [ ] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
    > ⚠️ Veuillez préciser dans la description pourquoi vous avez besoin de plus de temps pour présenter votre sujet. Pour information, les présentations longues ne sont pas prioritaires, car nous préférons avoir plusieurs présentations courtes pour les participants à l'événement.

- Niveau :
  - [ ] Débutant
  - [X] Intermédiaire
  - [ ] Avancé

## A propos de vous

- Nom et prénom : Chalopin Clément
- Contact (X / LinkedIn / Autre) : https://www.linkedin.com/in/clementchalopin/
- Entreprise : Freelance
- Rôle dans l'entreprise : Développeur Full Stack

**Comment by gpichot** [comment]
Hello @cchalop1, merci pour ta proposition, on est en train de regarder pour un meetup le mardi 18 juin, ce serait possible pour toi ?

**Comment by cchalop1** [comment]
Hello @gpichot, yes ! je serai disponible le 19 juin.

**Comment by gpichot** [comment]
@cchalop1 Le mardi 18 tu veux dire ? :D (Je te confirme ça fin de semaine prochaine)

**Comment by cchalop1** [comment]
Yes sorry ! 😅

**Comment by cchalop1** [comment]
Hello, en préparant, je pense m'approcher plus du format 10min. Qu'est-ce que tu en penses ?

**Comment by gpichot** [comment]
@cchalop1 Pas de soucis! Si tu as le temps tu peux rajouter une petite démo ? Non ?
Je te confirme pour le 18 juin dc ?

**Comment by cchalop1** [comment]
Je sais pas si c'est pertinent de faire une démo, mais je peux rajouter des exemples de code et essayer d'ouvrir sur l'utilisation qu'on peut faire de ces nouveautés pour m'approcher des 20 minutes. Oui c'est bon pour moi pour le 18 juin.

**Comment by gpichot** [comment]
C'est noté pour le 18, merci @cchalop1

**Comment by gpichot** [comment]
Hello @cchalop1, est-ce que tu peux m'envoyer une description en deux trois phrases de ton talk pour la comm ?
Merci d'avance pour ton retour.
Gabriel

**Comment by cchalop1** [comment]
Salut,

Je te propose "Quelles sont les nouveautés de React 19 et comment je peux les intégrer à ma codebase ? "

Qu'en penses-tu ? 

Clément

**Comment by gpichot** [comment]
@cchalop1 Si tu as quelque chose de plus long c'est mieux (même si c'est bateau).

Pour te donner une idée je te laisse regarder le carousel suivant (si c'est trop petit ça fait un peu vide).

https://www.linkedin.com/feed/update/urn:li:activity:7199488559353872385/

**Comment by gpichot** [comment]
Je ferme comme tu es passé à la session de juin dernier @cchalop1
