### ISSUE TITLE
Migration d'un Monolith Legacy vers un Monorepos Nx 

### ISSUE THREAD

**Issue by NicolasBelliard** [ReactParis/talks#5]
# Proposition de talk - React Paris

## Description du talk

- Titre : [REX] Migration d'un Monolith Legacy vers un Monorepos Nx avec Module Federation

- Contenu (Décrivez brièvement le contenu de la présentation) : 
  - Présentation du projet Legacy (en Perl/Mustache/jQuery) et de ses différents inconvenients.
  - Utilisation de Module Federation pour pouvoir splitter la plateforme en plusieurs micro-services.
  - Présentation de Nx et de ses avantages (cache locale, module boundaries, Nx Graph, ...).
  - Comment Nx a été utilisé pour faciliter la dev expérience sur la migration de notre monolith.

- Durée :

  - [x] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
    > ⚠️ Veuillez préciser dans la description pourquoi vous avez besoin de plus de temps pour présenter votre sujet. Pour information, les présentations longues ne sont pas prioritaires, car nous préférons avoir plusieurs présentations courtes pour les participants à l'événement.

- Niveau :
  - [x] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous

- Nom et prénom : Belliard Nicolas
- Contact (X / LinkedIn / Autre) : https://www.linkedin.com/in/nicolas-belliard-1a151a129/
- Entreprise : Splio
- Rôle dans l'entreprise : Senior FullStack Engineer

**Comment by gpichot** [comment]
Hello @NicolasBelliard tu serais dispo le 15 ou 17 septembre ?

**Comment by NicolasBelliard** [comment]
Hello @gpichot !
Oui je suis dispo.

**Comment by gpichot** [comment]
@NicolasBelliard Parfait 👌
Est-ce que tu pourras m'envoyer une description, titre de talk et ton intitulé pour la com ? (Ça nous permet de faire ce type de Carousel : https://www.linkedin.com/posts/gabrielpichot_react-paris-meetup-2-activity-7202334716916629504-IRY- )

**Comment by gpichot** [comment]
Pardon je m’étais trompé dans les dates. C’était le mardi 17 ou jeudi 19. 
est ce que le jeudi 19 du coup tu es dispo ? @NicolasBelliard

**Comment by NicolasBelliard** [comment]
Coucou @gpichot !
Oui pas de soucis, effectivement j'étais surpris que le meetup soit un dimanche :smile: 
Je t’envoie la description et le titre en fin de journée

**Comment by gpichot** [comment]
@NicolasBelliard m'oublies pas ;) Tu peux m'envoyer tout ça à gabriel@craftvalue.io

**Comment by NicolasBelliard** [comment]
@gpichot mail envoyé :)
