### ISSUE TITLE
React + ThreeJS = React Three Fiber

### ISSUE THREAD

**Issue by jeremt** [ReactParis/talks#6]
# Proposition de talk - React Paris

## Description du talk

- Titre : React + ThreeJS

- Contenu (Décrivez brièvement le contenu de la présentation) :

Le but de ce talk serait de présenter rapidement à travers une petite démo comment utiliser ThreeJS (pour faire de la 3d) en React avec la lib [react-three-fiber](https://docs.pmnd.rs/react-three-fiber/getting-started/introduction).
L'idée c'est de montrer les bases de la 3d mais surtout l'intérêt de combiner son utilisation à une library de component comme React.

- Durée :

  - [ ] Lightning (10 minutes)
  - [x] Regular (20 minutes)
  - [ ] Deep dive (40 minutes)
    > ⚠️ Veuillez préciser dans la description pourquoi vous avez besoin de plus de temps pour présenter votre sujet. Pour information, les présentations longues ne sont pas prioritaires, car nous préférons avoir plusieurs présentations courtes pour les participants à l'événement.

- Niveau :
  - [ ] Débutant
  - [x] Intermédiaire
  - [ ] Avancé

## A propos de vous

- Nom et prénom : Taboada Jérémie
- Contact (X / LinkedIn / Autre) : https://jeremt.github.io
- Entreprise : Indépendant
- Rôle dans l'entreprise : Formateur / Développeur Freelance

**Comment by gpichot** [comment]
Je ferme comme tu es passé à la session de juin dernier @jeremt
